---
- hosts: lb
  sudo: yes
  connection: local 
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - file: path=/etc/nginx/conf.d/default.conf state=absent
    - name: copy nginx.conf 
      template: src=nginx.conf dest=/etc/nginx/nginx.conf
    - name: start nginx
      service:
          name: nginx
          state: started
 